qa_knowledge_base = {
    "tell me about yourself": "A strong 'Tell me about yourself' answer should follow the Past-Present-Future formula. Briefly mention your background (Past), your current role and key responsibilities (Present), and why you're excited about this specific opportunity (Future). Aim for 90 seconds.",
    "why do you want to work here": "Focus on the company's specific values, products, or mission. For example: 'I've followed your work in AI-driven recruitment and am impressed by your commitment to bias reduction. My background in NLP aligns perfectly with your current scaling goals.'",
    "what are your strengths": "Identify 3 key strengths aligned with the job description. For each, provide a 'proof point'. Example: 'My primary strength is project management. At my last firm, I led a team of 5 to deliver a client portal 2 weeks ahead of schedule.'",
    "what are your weaknesses": "Select a real but non-critical skill you've improved. 'I used to find public speaking daunting, so I joined a local Toastmasters club. Now, I'm much more confident presenting technical data to non-technical stakeholders.'",
    "where do you see yourself in five years": "Balance ambition with realism. 'In five years, I hope to have mastered the technical stack here and be taking on more mentorship responsibilities, contributing to the team's long-term architectural decisions.'",
    "do you have any questions for me": "Ask high-level strategic questions. 'What does success look like for this role in the first 6 months?' or 'How does the engineering team balance new feature development with technical debt?'",
    "how do you handle pressure": "Show your process. 'I handle pressure by first breaking down the project into smaller, manageable tasks. I then prioritize them based on impact and deadlines, ensuring I communicate clearly with stakeholders throughout.'",
    "describe a challenging situation and how you overcame it": "Use the STAR method. 'Situation: We lost a key server during a launch. Task: Restore service immediately. Action: I led the rollback and implemented a new redundancy protocol. Result: Service restored in 15 mins with 0% data loss.'",
    "why did you leave your last job": "Keep it professional and forward-looking. 'I'm looking for a role that offers more opportunities to work with large-scale distributed systems, which is why your current infrastructure challenges interested me.'",
    "what are your salary expectations": "Research the market rate. 'Based on my experience and the current market for Senior Devs in this region, I'm looking for a range between $X and $Y, but I'm open to discussing the total compensation package.'",
    "what is your experience with python": "Python is my primary language. I've used it for building scalable APIs with FastAPI, data processing with Pandas, and even some automation scripts. I particularly enjoy its clean syntax and vast ecosystem.",
    "how do you stay updated with technology": "I'm an avid reader of engineering blogs like Netflix and Uber. I also contribute to open-source projects on GitHub and attend local tech meetups to stay connected with the latest industry trends.",
    "describe your ideal work environment": "I thrive in collaborative environments that value open communication, continuous learning, and a healthy balance between autonomy and team-wide architectural standards."
}
